#!/bin/sh

OUTPUT_DIR=$PWD/__build

./grammars/generate_plurals --mtgish-grammar  | jq . > ./grammars/mtgish_grammar-type_line.json5
./grammars/generate_plurals --english-grammar | jq . > ./grammars/english_grammar-type_line.json5

cd go_mtg_parser
  go build -o $OUTPUT_DIR/go_mtg_parser
cd ..

$OUTPUT_DIR/go_mtg_parser \
    --ignore-list-file ./grammars/ignore.json5 \
    --short-names-file ./grammars/short_names.json5 \
    --find-replace-file ./grammars/find_replace.json5 \
    --english-grammar-files ./grammars/english_grammar*.json5 \
    --mtgish-grammar-files ./grammars/mtgish_grammar*.json5 \
    --mtgjson-files ./data/oracle.json \
                    ./data/dungeons.json \
    --limit-to-subset ./data/debug.json5 \
    --debug-english \
    --debug-mtgish \
    --stop-after-first-failure
