#!/bin/sh

BASE_DIR=$PWD
BUILD_DIR=$PWD/__build
OUTPUT_DIR=$PWD/data

mkdir -p $OUTPUT_DIR

# -----------------------------------
# Download and process latest mtgjson
# -----------------------------------

MTGJSON_ATOMIC_CARDS_FILE=$BUILD_DIR/Mtgjson-AtomicCards-latest.json
MTGJSON_META_FILE=$BUILD_DIR/Mtgjson-Meta-latest.json

curl https://mtgjson.com/api/v5/Meta.json                  | jq . > $MTGJSON_META_FILE
curl https://mtgjson.com/api/v5/AtomicCards.json.xz | unxz | jq . > $MTGJSON_ATOMIC_CARDS_FILE

DATE=`jq -r ".meta | .version" $MTGJSON_META_FILE`
PROCESSED_FILE=Mtgjson-AtomicCards-$DATE.json

./preprocess_mtgjson $MTGJSON_ATOMIC_CARDS_FILE > $OUTPUT_DIR/oracle.json
