#!/bin/sh

OUTPUT_DIR=$PWD/__build
META_FILE=$OUTPUT_DIR/Meta-latest.json
MTGJSON=`jq -r ".meta | .version" $META_FILE`

cd go_mtg_parser
  go build -o $OUTPUT_DIR/go_mtg_parser
cd ..

$OUTPUT_DIR/go_mtg_parser \
    --ignore-list-file ./grammars/ignore.json5 \
    --short-names-file ./grammars/short_names.json5 \
    --find-replace-file ./grammars/find_replace.json5 \
    --english-grammar-files ./grammars/english_grammar*.json5 \
                            $OUTPUT_DIR/english_grammar-type_line.json \
    --mtgish-grammar-files ./grammars/mtgish_grammar*.json5 \
                           $OUTPUT_DIR/mtgish_grammar-type_line.json \
    --mtgjson-files $OUTPUT_DIR/AtomicCards-$MTGJSON.json \
                    ./data/AdditionalCards.json \
    --limit-to-subset ./data/debug.json5 \
    --print-english \
    --continue-after-failures
