
/// <reference types="./oracle_cards.d.ts" />

export const superTypeList: SuperType[] = [
  "Basic",
  "Legendary",
  "Ongoing",
  "Snow",
  "World"
]
export const cardTypeList: CardType[] = [
  "Artifact",
  "Battle",
  "Conspiracy",
  "Creature",
  "Dungeon",
  "Enchantment",
  "Instant",
  "Kindred",
  "Land",
  "Phenomenon",
  "Plane",
  "Planeswalker",
  "Scheme",
  "Sorcery",
  "Vanguard"
]
export const dungeonTypeList: DungeonType[] = [
  "Undercity"
]
export const battleTypeList: BattleType[] = [
  "Siege"
]
export const creatureTypeList: CreatureType[] = [
  "Advisor",
  "Aetherborn",
  "Alien",
  "Ally",
  "Angel",
  "Antelope",
  "Ape",
  "Archer",
  "Archon",
  "Armadillo",
  "Army",
  "Artificer",
  "Assassin",
  "AssemblyWorker",
  "Astartes",
  "Atog",
  "Aurochs",
  "Avatar",
  "Azra",
  "Badger",
  "Balloon",
  "Barbarian",
  "Bard",
  "Basilisk",
  "Bat",
  "Bear",
  "Beast",
  "Beaver",
  "Beeble",
  "Beholder",
  "Berserker",
  "Bird",
  "Bison",
  "Blinkmoth",
  "Boar",
  "Bringer",
  "Brushwagg",
  "Ctan",
  "Camarid",
  "Camel",
  "Capybara",
  "Caribou",
  "Carrier",
  "Cat",
  "Centaur",
  "Chimera",
  "Citizen",
  "Cleric",
  "Clown",
  "Cockatrice",
  "Construct",
  "Coward",
  "Coyote",
  "Crab",
  "Crocodile",
  "Custodes",
  "Cyberman",
  "Cyclops",
  "Dalek",
  "Dauthi",
  "Demigod",
  "Demon",
  "Deserter",
  "Detective",
  "Devil",
  "Dinosaur",
  "Djinn",
  "Doctor",
  "Dog",
  "Dragon",
  "Drake",
  "Dreadnought",
  "Drix",
  "Drone",
  "Druid",
  "Dryad",
  "Dwarf",
  "Efreet",
  "Egg",
  "Elder",
  "Eldrazi",
  "Elemental",
  "Elephant",
  "Elf",
  "Elk",
  "Echidna",
  "Employee",
  "Eye",
  "Faerie",
  "Ferret",
  "Fish",
  "Flagbearer",
  "Fox",
  "Fractal",
  "Frog",
  "Fungus",
  "Gamer",
  "Gamma",
  "Gargoyle",
  "Germ",
  "Giant",
  "Giraffe",
  "Gith",
  "Glimmer",
  "Gnoll",
  "Gnome",
  "Goat",
  "Goblin",
  "God",
  "Golem",
  "Gorgon",
  "Graveborn",
  "Gremlin",
  "Griffin",
  "Guest",
  "Hag",
  "Halfling",
  "Hamster",
  "Harpy",
  "Hedgehog",
  "Hellion",
  "Hero",
  "Hippo",
  "Hippogriff",
  "Homarid",
  "Homunculus",
  "Horror",
  "Horse",
  "Human",
  "Hydra",
  "Hyena",
  "Illusion",
  "Imp",
  "Incarnation",
  "Incubator",
  "Inkling",
  "Inquisitor",
  "Insect",
  "Jackal",
  "Jellyfish",
  "Juggernaut",
  "Kangaroo",
  "Kavu",
  "Kirin",
  "Kithkin",
  "Knight",
  "Kobold",
  "Kor",
  "Kraken",
  "Lamia",
  "Lammasu",
  "Leech",
  "Lemur",
  "Leviathan",
  "Lhurgoyf",
  "Licid",
  "Lizard",
  "Llama",
  "Lobster",
  "Manticore",
  "Masticore",
  "Mercenary",
  "Merfolk",
  "Metathran",
  "Minion",
  "Minotaur",
  "Mite",
  "Mole",
  "Monger",
  "Mongoose",
  "Monk",
  "Monkey",
  "Moogle",
  "Mount",
  "Moonfolk",
  "Mouse",
  "Mutant",
  "Myr",
  "Mystic",
  "Nautilus",
  "Necron",
  "Nephilim",
  "Nightmare",
  "Nightstalker",
  "Ninja",
  "Noble",
  "Noggle",
  "Nomad",
  "Nymph",
  "Octopus",
  "Ogre",
  "Ooze",
  "Orb",
  "Orc",
  "Orgg",
  "Otter",
  "Ouphe",
  "Ox",
  "Oyster",
  "Pangolin",
  "Peasant",
  "Pegasus",
  "Pentavite",
  "Performer",
  "Pest",
  "Phelddagrif",
  "Phoenix",
  "Phyrexian",
  "Pilot",
  "Pincher",
  "Pirate",
  "Plant",
  "Platypus",
  "Porcupine",
  "Possum",
  "Praetor",
  "Primarch",
  "Prism",
  "Processor",
  "Rabbit",
  "Raccoon",
  "Ranger",
  "Rat",
  "Rebel",
  "Reflection",
  "Rhino",
  "Rigger",
  "Robot",
  "Rogue",
  "Qu",
  "Sable",
  "Salamander",
  "Samurai",
  "Sand",
  "Saproling",
  "Satyr",
  "Scarecrow",
  "Scientist",
  "Scion",
  "Scorpion",
  "Scout",
  "Sculpture",
  "Seal",
  "Serf",
  "Serpent",
  "Servo",
  "Shade",
  "Shaman",
  "Shapeshifter",
  "Shark",
  "Sheep",
  "Siren",
  "Skeleton",
  "Skrull",
  "Skunk",
  "Slith",
  "Sliver",
  "Sloth",
  "Slug",
  "Snail",
  "Snake",
  "Soldier",
  "Soltari",
  "Sorcerer",
  "Spawn",
  "Specter",
  "Spellshaper",
  "Sphinx",
  "Spider",
  "Spike",
  "Spirit",
  "Splinter",
  "Sponge",
  "Squid",
  "Squirrel",
  "Starfish",
  "Surrakar",
  "Survivor",
  "Symbiote",
  "Synth",
  "Tentacle",
  "Tetravite",
  "Thalakos",
  "Thopter",
  "Thrull",
  "Tiefling",
  "TimeLord",
  "Toy",
  "Treefolk",
  "Trilobite",
  "Triskelavite",
  "Troll",
  "Turtle",
  "Tyranid",
  "Unicorn",
  "Utrom",
  "Vampire",
  "Varmint",
  "Vedalken",
  "Villain",
  "Volver",
  "Wall",
  "Walrus",
  "Warlock",
  "Warrior",
  "Weasel",
  "Weird",
  "Werewolf",
  "Whale",
  "Wizard",
  "Wolf",
  "Wolverine",
  "Wombat",
  "Worm",
  "Wraith",
  "Wurm",
  "Yeti",
  "Zombie",
  "Zubera"
]
export const landTypeList: LandType[] = [
  "Cave",
  "Desert",
  "Forest",
  "Gate",
  "Island",
  "Lair",
  "Locus",
  "Mine",
  "Mountain",
  "Planet",
  "Plains",
  "PowerPlant",
  "Sphere",
  "Swamp",
  "Tower",
  "Town",
  "Urzas"
]
export const spellTypeList: SpellType[] = [
  "Adventure",
  "Omen",
  "Arcane",
  "Lesson",
  "Chorus",
  "Trap"
]
export const enchantmentTypeList: EnchantmentType[] = [
  "Aura",
  "Background",
  "Cartouche",
  "Case",
  "Class",
  "Curse",
  "Plan",
  "Room",
  "Rune",
  "Saga",
  "Shard",
  "Shrine"
]
export const artifactTypeList: ArtifactType[] = [
  "Attraction",
  "Blood",
  "Bobblehead",
  "Book",
  "Clue",
  "Equipment",
  "Food",
  "Fortification",
  "Infinity",
  "Junk",
  "Powerstone",
  "Lander",
  "Spacecraft",
  "Stone",
  "Treasure",
  "Vehicle"
]
export const planeswalkerTypeList: PlaneswalkerType[] = [
  "Ajani",
  "Aminatou",
  "Angrath",
  "Arlinn",
  "Ashiok",
  "Bahamut",
  "Basri",
  "Bolas",
  "Calix",
  "Chandra",
  "Comet",
  "Dack",
  "Dakkon",
  "Daretti",
  "Davriel",
  "Deb",
  "Dellian",
  "Dihada",
  "Domri",
  "Dovin",
  "Ellywick",
  "Elminster",
  "Elspeth",
  "Estrid",
  "Freyalise",
  "Garruk",
  "Gideon",
  "Grist",
  "Guff",
  "Huatli",
  "Jace",
  "Jared",
  "Jaya",
  "Jeska",
  "Kaito",
  "Karn",
  "Kasmina",
  "Kaya",
  "Kiora",
  "Koth",
  "Liliana",
  "Lolth",
  "Lukka",
  "Minsc",
  "Mordenkainen",
  "Nahiri",
  "Narset",
  "Niko",
  "Nissa",
  "Nixilis",
  "Oko",
  "Quintorius",
  "Ral",
  "Rowan",
  "Saheeli",
  "Samut",
  "Sarkhan",
  "Serra",
  "Sivitri",
  "Sorin",
  "Szat",
  "Tamiyo",
  "Tasha",
  "Teferi",
  "Teyo",
  "Tezzeret",
  "Tibalt",
  "Tyvar",
  "Ugin",
  "Urza",
  "Venser",
  "Vivien",
  "Vraska",
  "Vronos",
  "Will",
  "Windgrace",
  "Wrenn",
  "Xenagos",
  "Yanggu",
  "Yanling",
  "Zariel"
]
export const planeTypeList: PlaneType[] = [
  "Alara",
  "AlfavaMetraxis",
  "Amonkhet",
  "AndrozaniMinor",
  "Antausia",
  "Apalapucia",
  "Arcavios",
  "Arkhos",
  "Avishkar",
  "Azgol",
  "Belenon",
  "BolassMeditationRealm",
  "Capenna",
  "Cridhe",
  "Darillium",
  "Dominaria",
  "Earth",
  "Echoir",
  "Eldraine",
  "Equilor",
  "Ergamon",
  "Fabacin",
  "Fiora",
  "Gallifrey",
  "Gargantikar",
  "Gobakhan",
  "HorseheadNebula",
  "Ikoria",
  "Innistrad",
  "Iquatana",
  "Ir",
  "Ixalan",
  "Kaldheim",
  "Kamigawa",
  "Kandoka",
  "Karsus",
  "Kephalai",
  "Kinshala",
  "Kolbahan",
  "Kylem",
  "Kyneth",
  "Lorwyn",
  "Luvion",
  "Mars",
  "Mercadia",
  "Mirrodin",
  "Moag",
  "Mongseng",
  "Moon",
  "Muraganda",
  "Necros",
  "NewEarth",
  "NewPhyrexia",
  "OutsideMuttersSpiral",
  "Phyrexia",
  "Pyrulea",
  "Rabiah",
  "Rath",
  "Ravnica",
  "Regatha",
  "Segovia",
  "SerrasRealm",
  "Shadowmoor",
  "Shandalar",
  "Shenmeng",
  "Skaro",
  "Spaceship",
  "Tarkir",
  "TheAbyss",
  "TheDalekAsylum",
  "TheLibrary",
  "Theros",
  "Time",
  "Trenzalore",
  "UnknownPlanet",
  "Ulgrotha",
  "Valla",
  "Vryn",
  "Wildfire",
  "Xerex",
  "Zendikar",
  "Zhalfir"
]

export const subtype_strings: Map<SubType, string> = new Map([
  ["Undercity", "Undercity"],
  ["Siege", "Siege"],
  ["Advisor", "Advisor"],
  ["Aetherborn", "Aetherborn"],
  ["Alien", "Alien"],
  ["Ally", "Ally"],
  ["Angel", "Angel"],
  ["Antelope", "Antelope"],
  ["Ape", "Ape"],
  ["Archer", "Archer"],
  ["Archon", "Archon"],
  ["Armadillo", "Armadillo"],
  ["Army", "Army"],
  ["Artificer", "Artificer"],
  ["Assassin", "Assassin"],
  ["AssemblyWorker", "Assembly-Worker"],
  ["Astartes", "Astartes"],
  ["Atog", "Atog"],
  ["Aurochs", "Aurochs"],
  ["Avatar", "Avatar"],
  ["Azra", "Azra"],
  ["Badger", "Badger"],
  ["Balloon", "Balloon"],
  ["Barbarian", "Barbarian"],
  ["Bard", "Bard"],
  ["Basilisk", "Basilisk"],
  ["Bat", "Bat"],
  ["Bear", "Bear"],
  ["Beast", "Beast"],
  ["Beaver", "Beaver"],
  ["Beeble", "Beeble"],
  ["Beholder", "Beholder"],
  ["Berserker", "Berserker"],
  ["Bird", "Bird"],
  ["Bison", "Bison"],
  ["Blinkmoth", "Blinkmoth"],
  ["Boar", "Boar"],
  ["Bringer", "Bringer"],
  ["Brushwagg", "Brushwagg"],
  ["Ctan", "C'tan"],
  ["Camarid", "Camarid"],
  ["Camel", "Camel"],
  ["Capybara", "Capybara"],
  ["Caribou", "Caribou"],
  ["Carrier", "Carrier"],
  ["Cat", "Cat"],
  ["Centaur", "Centaur"],
  ["Chimera", "Chimera"],
  ["Citizen", "Citizen"],
  ["Cleric", "Cleric"],
  ["Clown", "Clown"],
  ["Cockatrice", "Cockatrice"],
  ["Construct", "Construct"],
  ["Coward", "Coward"],
  ["Coyote", "Coyote"],
  ["Crab", "Crab"],
  ["Crocodile", "Crocodile"],
  ["Custodes", "Custodes"],
  ["Cyberman", "Cyberman"],
  ["Cyclops", "Cyclops"],
  ["Dalek", "Dalek"],
  ["Dauthi", "Dauthi"],
  ["Demigod", "Demigod"],
  ["Demon", "Demon"],
  ["Deserter", "Deserter"],
  ["Detective", "Detective"],
  ["Devil", "Devil"],
  ["Dinosaur", "Dinosaur"],
  ["Djinn", "Djinn"],
  ["Doctor", "Doctor"],
  ["Dog", "Dog"],
  ["Dragon", "Dragon"],
  ["Drake", "Drake"],
  ["Dreadnought", "Dreadnought"],
  ["Drix", "Drix"],
  ["Drone", "Drone"],
  ["Druid", "Druid"],
  ["Dryad", "Dryad"],
  ["Dwarf", "Dwarf"],
  ["Efreet", "Efreet"],
  ["Egg", "Egg"],
  ["Elder", "Elder"],
  ["Eldrazi", "Eldrazi"],
  ["Elemental", "Elemental"],
  ["Elephant", "Elephant"],
  ["Elf", "Elf"],
  ["Elk", "Elk"],
  ["Echidna", "Echidna"],
  ["Employee", "Employee"],
  ["Eye", "Eye"],
  ["Faerie", "Faerie"],
  ["Ferret", "Ferret"],
  ["Fish", "Fish"],
  ["Flagbearer", "Flagbearer"],
  ["Fox", "Fox"],
  ["Fractal", "Fractal"],
  ["Frog", "Frog"],
  ["Fungus", "Fungus"],
  ["Gamer", "Gamer"],
  ["Gamma", "Gamma"],
  ["Gargoyle", "Gargoyle"],
  ["Germ", "Germ"],
  ["Giant", "Giant"],
  ["Giraffe", "Giraffe"],
  ["Gith", "Gith"],
  ["Glimmer", "Glimmer"],
  ["Gnoll", "Gnoll"],
  ["Gnome", "Gnome"],
  ["Goat", "Goat"],
  ["Goblin", "Goblin"],
  ["God", "God"],
  ["Golem", "Golem"],
  ["Gorgon", "Gorgon"],
  ["Graveborn", "Graveborn"],
  ["Gremlin", "Gremlin"],
  ["Griffin", "Griffin"],
  ["Guest", "Guest"],
  ["Hag", "Hag"],
  ["Halfling", "Halfling"],
  ["Hamster", "Hamster"],
  ["Harpy", "Harpy"],
  ["Hedgehog", "Hedgehog"],
  ["Hellion", "Hellion"],
  ["Hero", "Hero"],
  ["Hippo", "Hippo"],
  ["Hippogriff", "Hippogriff"],
  ["Homarid", "Homarid"],
  ["Homunculus", "Homunculus"],
  ["Horror", "Horror"],
  ["Horse", "Horse"],
  ["Human", "Human"],
  ["Hydra", "Hydra"],
  ["Hyena", "Hyena"],
  ["Illusion", "Illusion"],
  ["Imp", "Imp"],
  ["Incarnation", "Incarnation"],
  ["Incubator", "Incubator"],
  ["Inkling", "Inkling"],
  ["Inquisitor", "Inquisitor"],
  ["Insect", "Insect"],
  ["Jackal", "Jackal"],
  ["Jellyfish", "Jellyfish"],
  ["Juggernaut", "Juggernaut"],
  ["Kangaroo", "Kangaroo"],
  ["Kavu", "Kavu"],
  ["Kirin", "Kirin"],
  ["Kithkin", "Kithkin"],
  ["Knight", "Knight"],
  ["Kobold", "Kobold"],
  ["Kor", "Kor"],
  ["Kraken", "Kraken"],
  ["Lamia", "Lamia"],
  ["Lammasu", "Lammasu"],
  ["Leech", "Leech"],
  ["Lemur", "Lemur"],
  ["Leviathan", "Leviathan"],
  ["Lhurgoyf", "Lhurgoyf"],
  ["Licid", "Licid"],
  ["Lizard", "Lizard"],
  ["Llama", "Llama"],
  ["Lobster", "Lobster"],
  ["Manticore", "Manticore"],
  ["Masticore", "Masticore"],
  ["Mercenary", "Mercenary"],
  ["Merfolk", "Merfolk"],
  ["Metathran", "Metathran"],
  ["Minion", "Minion"],
  ["Minotaur", "Minotaur"],
  ["Mite", "Mite"],
  ["Mole", "Mole"],
  ["Monger", "Monger"],
  ["Mongoose", "Mongoose"],
  ["Monk", "Monk"],
  ["Monkey", "Monkey"],
  ["Moogle", "Moogle"],
  ["Mount", "Mount"],
  ["Moonfolk", "Moonfolk"],
  ["Mouse", "Mouse"],
  ["Mutant", "Mutant"],
  ["Myr", "Myr"],
  ["Mystic", "Mystic"],
  ["Nautilus", "Nautilus"],
  ["Necron", "Necron"],
  ["Nephilim", "Nephilim"],
  ["Nightmare", "Nightmare"],
  ["Nightstalker", "Nightstalker"],
  ["Ninja", "Ninja"],
  ["Noble", "Noble"],
  ["Noggle", "Noggle"],
  ["Nomad", "Nomad"],
  ["Nymph", "Nymph"],
  ["Octopus", "Octopus"],
  ["Ogre", "Ogre"],
  ["Ooze", "Ooze"],
  ["Orb", "Orb"],
  ["Orc", "Orc"],
  ["Orgg", "Orgg"],
  ["Otter", "Otter"],
  ["Ouphe", "Ouphe"],
  ["Ox", "Ox"],
  ["Oyster", "Oyster"],
  ["Pangolin", "Pangolin"],
  ["Peasant", "Peasant"],
  ["Pegasus", "Pegasus"],
  ["Pentavite", "Pentavite"],
  ["Performer", "Performer"],
  ["Pest", "Pest"],
  ["Phelddagrif", "Phelddagrif"],
  ["Phoenix", "Phoenix"],
  ["Phyrexian", "Phyrexian"],
  ["Pilot", "Pilot"],
  ["Pincher", "Pincher"],
  ["Pirate", "Pirate"],
  ["Plant", "Plant"],
  ["Platypus", "Platypus"],
  ["Porcupine", "Porcupine"],
  ["Possum", "Possum"],
  ["Praetor", "Praetor"],
  ["Primarch", "Primarch"],
  ["Prism", "Prism"],
  ["Processor", "Processor"],
  ["Rabbit", "Rabbit"],
  ["Raccoon", "Raccoon"],
  ["Ranger", "Ranger"],
  ["Rat", "Rat"],
  ["Rebel", "Rebel"],
  ["Reflection", "Reflection"],
  ["Rhino", "Rhino"],
  ["Rigger", "Rigger"],
  ["Robot", "Robot"],
  ["Rogue", "Rogue"],
  ["Qu", "Qu"],
  ["Sable", "Sable"],
  ["Salamander", "Salamander"],
  ["Samurai", "Samurai"],
  ["Sand", "Sand"],
  ["Saproling", "Saproling"],
  ["Satyr", "Satyr"],
  ["Scarecrow", "Scarecrow"],
  ["Scientist", "Scientist"],
  ["Scion", "Scion"],
  ["Scorpion", "Scorpion"],
  ["Scout", "Scout"],
  ["Sculpture", "Sculpture"],
  ["Seal", "Seal"],
  ["Serf", "Serf"],
  ["Serpent", "Serpent"],
  ["Servo", "Servo"],
  ["Shade", "Shade"],
  ["Shaman", "Shaman"],
  ["Shapeshifter", "Shapeshifter"],
  ["Shark", "Shark"],
  ["Sheep", "Sheep"],
  ["Siren", "Siren"],
  ["Skeleton", "Skeleton"],
  ["Skrull", "Skrull"],
  ["Skunk", "Skunk"],
  ["Slith", "Slith"],
  ["Sliver", "Sliver"],
  ["Sloth", "Sloth"],
  ["Slug", "Slug"],
  ["Snail", "Snail"],
  ["Snake", "Snake"],
  ["Soldier", "Soldier"],
  ["Soltari", "Soltari"],
  ["Sorcerer", "Sorcerer"],
  ["Spawn", "Spawn"],
  ["Specter", "Specter"],
  ["Spellshaper", "Spellshaper"],
  ["Sphinx", "Sphinx"],
  ["Spider", "Spider"],
  ["Spike", "Spike"],
  ["Spirit", "Spirit"],
  ["Splinter", "Splinter"],
  ["Sponge", "Sponge"],
  ["Squid", "Squid"],
  ["Squirrel", "Squirrel"],
  ["Starfish", "Starfish"],
  ["Surrakar", "Surrakar"],
  ["Survivor", "Survivor"],
  ["Symbiote", "Symbiote"],
  ["Synth", "Synth"],
  ["Tentacle", "Tentacle"],
  ["Tetravite", "Tetravite"],
  ["Thalakos", "Thalakos"],
  ["Thopter", "Thopter"],
  ["Thrull", "Thrull"],
  ["Tiefling", "Tiefling"],
  ["TimeLord", "Time Lord"],
  ["Toy", "Toy"],
  ["Treefolk", "Treefolk"],
  ["Trilobite", "Trilobite"],
  ["Triskelavite", "Triskelavite"],
  ["Troll", "Troll"],
  ["Turtle", "Turtle"],
  ["Tyranid", "Tyranid"],
  ["Unicorn", "Unicorn"],
  ["Utrom", "Utrom"],
  ["Vampire", "Vampire"],
  ["Varmint", "Varmint"],
  ["Vedalken", "Vedalken"],
  ["Villain", "Villain"],
  ["Volver", "Volver"],
  ["Wall", "Wall"],
  ["Walrus", "Walrus"],
  ["Warlock", "Warlock"],
  ["Warrior", "Warrior"],
  ["Weasel", "Weasel"],
  ["Weird", "Weird"],
  ["Werewolf", "Werewolf"],
  ["Whale", "Whale"],
  ["Wizard", "Wizard"],
  ["Wolf", "Wolf"],
  ["Wolverine", "Wolverine"],
  ["Wombat", "Wombat"],
  ["Worm", "Worm"],
  ["Wraith", "Wraith"],
  ["Wurm", "Wurm"],
  ["Yeti", "Yeti"],
  ["Zombie", "Zombie"],
  ["Zubera", "Zubera"],
  ["Cave", "Cave"],
  ["Desert", "Desert"],
  ["Forest", "Forest"],
  ["Gate", "Gate"],
  ["Island", "Island"],
  ["Lair", "Lair"],
  ["Locus", "Locus"],
  ["Mine", "Mine"],
  ["Mountain", "Mountain"],
  ["Planet", "Planet"],
  ["Plains", "Plains"],
  ["PowerPlant", "Power-Plant"],
  ["Sphere", "Sphere"],
  ["Swamp", "Swamp"],
  ["Tower", "Tower"],
  ["Town", "Town"],
  ["Urzas", "Urza's"],
  ["Adventure", "Adventure"],
  ["Omen", "Omen"],
  ["Arcane", "Arcane"],
  ["Lesson", "Lesson"],
  ["Chorus", "Chorus"],
  ["Trap", "Trap"],
  ["Aura", "Aura"],
  ["Background", "Background"],
  ["Cartouche", "Cartouche"],
  ["Case", "Case"],
  ["Class", "Class"],
  ["Curse", "Curse"],
  ["Plan", "Plan"],
  ["Room", "Room"],
  ["Rune", "Rune"],
  ["Saga", "Saga"],
  ["Shard", "Shard"],
  ["Shrine", "Shrine"],
  ["Attraction", "Attraction"],
  ["Blood", "Blood"],
  ["Bobblehead", "Bobblehead"],
  ["Book", "Book"],
  ["Clue", "Clue"],
  ["Equipment", "Equipment"],
  ["Food", "Food"],
  ["Fortification", "Fortification"],
  ["Infinity", "Infinity"],
  ["Junk", "Junk"],
  ["Powerstone", "Powerstone"],
  ["Lander", "Lander"],
  ["Spacecraft", "Spacecraft"],
  ["Stone", "Stone"],
  ["Treasure", "Treasure"],
  ["Vehicle", "Vehicle"],
  ["Ajani", "Ajani"],
  ["Aminatou", "Aminatou"],
  ["Angrath", "Angrath"],
  ["Arlinn", "Arlinn"],
  ["Ashiok", "Ashiok"],
  ["Bahamut", "Bahamut"],
  ["Basri", "Basri"],
  ["Bolas", "Bolas"],
  ["Calix", "Calix"],
  ["Chandra", "Chandra"],
  ["Comet", "Comet"],
  ["Dack", "Dack"],
  ["Dakkon", "Dakkon"],
  ["Daretti", "Daretti"],
  ["Davriel", "Davriel"],
  ["Deb", "Deb"],
  ["Dellian", "Dellian"],
  ["Dihada", "Dihada"],
  ["Domri", "Domri"],
  ["Dovin", "Dovin"],
  ["Ellywick", "Ellywick"],
  ["Elminster", "Elminster"],
  ["Elspeth", "Elspeth"],
  ["Estrid", "Estrid"],
  ["Freyalise", "Freyalise"],
  ["Garruk", "Garruk"],
  ["Gideon", "Gideon"],
  ["Grist", "Grist"],
  ["Guff", "Guff"],
  ["Huatli", "Huatli"],
  ["Jace", "Jace"],
  ["Jared", "Jared"],
  ["Jaya", "Jaya"],
  ["Jeska", "Jeska"],
  ["Kaito", "Kaito"],
  ["Karn", "Karn"],
  ["Kasmina", "Kasmina"],
  ["Kaya", "Kaya"],
  ["Kiora", "Kiora"],
  ["Koth", "Koth"],
  ["Liliana", "Liliana"],
  ["Lolth", "Lolth"],
  ["Lukka", "Lukka"],
  ["Minsc", "Minsc"],
  ["Mordenkainen", "Mordenkainen"],
  ["Nahiri", "Nahiri"],
  ["Narset", "Narset"],
  ["Niko", "Niko"],
  ["Nissa", "Nissa"],
  ["Nixilis", "Nixilis"],
  ["Oko", "Oko"],
  ["Quintorius", "Quintorius"],
  ["Ral", "Ral"],
  ["Rowan", "Rowan"],
  ["Saheeli", "Saheeli"],
  ["Samut", "Samut"],
  ["Sarkhan", "Sarkhan"],
  ["Serra", "Serra"],
  ["Sivitri", "Sivitri"],
  ["Sorin", "Sorin"],
  ["Szat", "Szat"],
  ["Tamiyo", "Tamiyo"],
  ["Tasha", "Tasha"],
  ["Teferi", "Teferi"],
  ["Teyo", "Teyo"],
  ["Tezzeret", "Tezzeret"],
  ["Tibalt", "Tibalt"],
  ["Tyvar", "Tyvar"],
  ["Ugin", "Ugin"],
  ["Urza", "Urza"],
  ["Venser", "Venser"],
  ["Vivien", "Vivien"],
  ["Vraska", "Vraska"],
  ["Vronos", "Vronos"],
  ["Will", "Will"],
  ["Windgrace", "Windgrace"],
  ["Wrenn", "Wrenn"],
  ["Xenagos", "Xenagos"],
  ["Yanggu", "Yanggu"],
  ["Yanling", "Yanling"],
  ["Zariel", "Zariel"],
  ["Alara", "Alara"],
  ["AlfavaMetraxis", "Alfava Metraxis"],
  ["Amonkhet", "Amonkhet"],
  ["AndrozaniMinor", "Androzani Minor"],
  ["Antausia", "Antausia"],
  ["Apalapucia", "Apalapucia"],
  ["Arcavios", "Arcavios"],
  ["Arkhos", "Arkhos"],
  ["Avishkar", "Avishkar"],
  ["Azgol", "Azgol"],
  ["Belenon", "Belenon"],
  ["BolassMeditationRealm", "Bolas's Meditation Realm"],
  ["Capenna", "Capenna"],
  ["Cridhe", "Cridhe"],
  ["Darillium", "Darillium"],
  ["Dominaria", "Dominaria"],
  ["Earth", "Earth"],
  ["Echoir", "Echoir"],
  ["Eldraine", "Eldraine"],
  ["Equilor", "Equilor"],
  ["Ergamon", "Ergamon"],
  ["Fabacin", "Fabacin"],
  ["Fiora", "Fiora"],
  ["Gallifrey", "Gallifrey"],
  ["Gargantikar", "Gargantikar"],
  ["Gobakhan", "Gobakhan"],
  ["HorseheadNebula", "Horsehead Nebula"],
  ["Ikoria", "Ikoria"],
  ["Innistrad", "Innistrad"],
  ["Iquatana", "Iquatana"],
  ["Ir", "Ir"],
  ["Ixalan", "Ixalan"],
  ["Kaldheim", "Kaldheim"],
  ["Kamigawa", "Kamigawa"],
  ["Kandoka", "Kandoka"],
  ["Karsus", "Karsus"],
  ["Kephalai", "Kephalai"],
  ["Kinshala", "Kinshala"],
  ["Kolbahan", "Kolbahan"],
  ["Kylem", "Kylem"],
  ["Kyneth", "Kyneth"],
  ["Lorwyn", "Lorwyn"],
  ["Luvion", "Luvion"],
  ["Mars", "Mars"],
  ["Mercadia", "Mercadia"],
  ["Mirrodin", "Mirrodin"],
  ["Moag", "Moag"],
  ["Mongseng", "Mongseng"],
  ["Moon", "Moon"],
  ["Muraganda", "Muraganda"],
  ["Necros", "Necros"],
  ["NewEarth", "New Earth"],
  ["NewPhyrexia", "New Phyrexia"],
  ["OutsideMuttersSpiral", "Outside Mutter's Spiral"],
  ["Phyrexia", "Phyrexia"],
  ["Pyrulea", "Pyrulea"],
  ["Rabiah", "Rabiah"],
  ["Rath", "Rath"],
  ["Ravnica", "Ravnica"],
  ["Regatha", "Regatha"],
  ["Segovia", "Segovia"],
  ["SerrasRealm", "Serra's Realm"],
  ["Shadowmoor", "Shadowmoor"],
  ["Shandalar", "Shandalar"],
  ["Shenmeng", "Shenmeng"],
  ["Skaro", "Skaro"],
  ["Spaceship", "Spaceship"],
  ["Tarkir", "Tarkir"],
  ["TheAbyss", "The Abyss"],
  ["TheDalekAsylum", "The Dalek Asylum"],
  ["TheLibrary", "The Library"],
  ["Theros", "Theros"],
  ["Time", "Time"],
  ["Trenzalore", "Trenzalore"],
  ["UnknownPlanet", "Unknown Planet"],
  ["Ulgrotha", "Ulgrotha"],
  ["Valla", "Valla"],
  ["Vryn", "Vryn"],
  ["Wildfire", "Wildfire"],
  ["Xerex", "Xerex"],
  ["Zendikar", "Zendikar"],
  ["Zhalfir", "Zhalfir"]
])

